server:
  port: 8080

spring:
  datasource:
    name: haokes
    url: jdbc:mysql://39.96.209.215:3306/haoke
    username: yangzixin
    password: yangyang0.0
    #driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml  #ע�⣺һ��Ҫ��Ӧmapperӳ��xml�ļ�������·��
  type-aliases-package: com.haoke.yang.bean  # ע�⣺��Ӧʵ�����·��
